"""Add ScriptLabels table

Revision ID: 2064b79d481b
Revises: 3b0618e3a9f5
Create Date: 2024-06-21 19:16:42.549293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2064b79d481b'
down_revision = '3b0618e3a9f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('script_labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('script_name', sa.String(length=100), nullable=False),
    sa.Column('labels', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),\
    sa.UniqueConstraint('script_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('script_labels')
    # ### end Alembic commands ###
